/**
 * Business types catalog for iAgend.
 * Each type defines event options, special request chips, and UI labels
 * that are contextually appropriate for that type of establishment.
 */

export interface EventType {
  emoji: string
  label: string
}

export interface BusinessTypeConfig {
  value: string
  label: string
  category: string
  partySizeLabel: string
  partySizeSublabel: string
  eventTypes: EventType[]
  specialChips: string[]
  specialRequestsPlaceholder: string
}

export const BUSINESS_TYPE_CONFIGS: Record<string, BusinessTypeConfig> = {
  restaurante: {
    value: "restaurante",
    label: "Restaurante",
    category: "Gastronomia",
    partySizeLabel: "Comensales",
    partySizeSublabel: "Selecciona la cantidad de personas.",
    eventTypes: [
      { emoji: "Plato", label: "Cena casual" },
      { emoji: "Pareja", label: "Cena romantica" },
      { emoji: "Torta", label: "Cumpleanos" },
      { emoji: "Copa", label: "Aniversario" },
      { emoji: "Maletín", label: "Negocios" },
      { emoji: "Fiesta", label: "Celebracion" },
    ],
    specialChips: ["Silla para bebe", "Accesibilidad", "Mesa tranquila", "Vista panoramica", "Alergias"],
    specialRequestsPlaceholder: "Solicitudes adicionales (alergias, mesa preferida, coche bebe)...",
  },
  bar: {
    value: "bar",
    label: "Bar / Pub",
    category: "Gastronomia",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Cerveza", label: "Reunion informal" },
      { emoji: "Copa", label: "Celebracion" },
      { emoji: "Torta", label: "Cumpleanos" },
      { emoji: "Nota", label: "Noche de musica" },
      { emoji: "TV", label: "Ver partido" },
      { emoji: "Brindis", label: "Despedida" },
    ],
    specialChips: ["Mesa reservada", "Zona VIP", "Sin ruido", "Accesibilidad", "Botella compartida"],
    specialRequestsPlaceholder: "Solicitudes adicionales (zona preferida, decoracion, bebidas especiales)...",
  },
  cafe: {
    value: "cafe",
    label: "Cafeteria",
    category: "Gastronomia",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Cafe", label: "Reunion casual" },
      { emoji: "Portatil", label: "Trabajo remoto" },
      { emoji: "Libro", label: "Estudio" },
      { emoji: "Negocio", label: "Reunion de negocios" },
      { emoji: "Amigos", label: "Encuentro amigos" },
      { emoji: "Fecha", label: "Cita romantica" },
    ],
    specialChips: ["Mesa de trabajo", "Toma corriente", "Zona tranquila", "Accesibilidad", "Mesa exterior"],
    specialRequestsPlaceholder: "Solicitudes adicionales (mesa con toma corriente, zona tranquila)...",
  },
  fast_food: {
    value: "fast_food",
    label: "Comida Rapida",
    category: "Gastronomia",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Hamburguesa", label: "Almuerzo rapido" },
      { emoji: "Familia", label: "Reunion familiar" },
      { emoji: "Torta", label: "Cumpleanos" },
      { emoji: "Ninos", label: "Salida con ninos" },
      { emoji: "Amigos", label: "Salida con amigos" },
      { emoji: "Trabajo", label: "Hora del almuerzo" },
    ],
    specialChips: ["Silla para bebe", "Area infantil", "Accesibilidad", "Para llevar", "Alergias"],
    specialRequestsPlaceholder: "Solicitudes adicionales (alergias, area infantil)...",
  },
  clinica_dental: {
    value: "clinica_dental",
    label: "Clinica Dental",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeSublabel: "Selecciona el numero de pacientes.",
    eventTypes: [
      { emoji: "Diente", label: "Limpieza dental" },
      { emoji: "Brackets", label: "Ortodoncia" },
      { emoji: "Brillo", label: "Blanqueamiento" },
      { emoji: "Medico", label: "Consulta general" },
      { emoji: "Raiz", label: "Endodoncia" },
      { emoji: "Sonrisa", label: "Diseno de sonrisa" },
    ],
    specialChips: ["Primera vez", "Control post-tratamiento", "Urgencia dental", "Paciente menor de edad", "Fobia al dentista"],
    specialRequestsPlaceholder: "Detalles adicionales (tratamiento previo, alergias a anestesia, urgencia)...",
  },
  consultorio_medico: {
    value: "consultorio_medico",
    label: "Consultorio Medico",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeSublabel: "Selecciona el numero de pacientes.",
    eventTypes: [
      { emoji: "Medico", label: "Consulta general" },
      { emoji: "Control", label: "Control medico" },
      { emoji: "Resultado", label: "Entrega de resultados" },
      { emoji: "Especialista", label: "Especialista" },
      { emoji: "Preventivo", label: "Chequeo preventivo" },
      { emoji: "Urgencia", label: "Urgencia medica" },
    ],
    specialChips: ["Primera vez", "Control periodico", "Remision especialista", "Traer examenes", "Paciente con movilidad reducida"],
    specialRequestsPlaceholder: "Detalles adicionales (motivo de consulta, medicamentos actuales, alergias)...",
  },
  centro_estetica: {
    value: "centro_estetica",
    label: "Centro de Estetica / Spa",
    category: "Salud y Belleza",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Spa", label: "Sesion de spa" },
      { emoji: "Masaje", label: "Masaje relajante" },
      { emoji: "Facial", label: "Tratamiento facial" },
      { emoji: "Cuerpo", label: "Tratamiento corporal" },
      { emoji: "Pareja", label: "Spa en pareja" },
      { emoji: "Cumple", label: "Cumpleanos spa" },
    ],
    specialChips: ["Primera vez", "Embarazada", "Piel sensible", "Alergias a productos", "Servicio de pareja"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de piel, alergias a productos, preferencia de terapeuta)...",
  },
  psicologia: {
    value: "psicologia",
    label: "Psicologo / Terapeuta",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeSublabel: "Selecciona el numero de pacientes.",
    eventTypes: [
      { emoji: "Mente", label: "Consulta individual" },
      { emoji: "Pareja", label: "Terapia de pareja" },
      { emoji: "Familia", label: "Terapia familiar" },
      { emoji: "Nino", label: "Psicologia infantil" },
      { emoji: "Trabajo", label: "Psicologia laboral" },
      { emoji: "Evaluacion", label: "Evaluacion psicologica" },
    ],
    specialChips: ["Primera vez", "Derivacion medica", "Crisis emocional", "Modalidad virtual", "Confidencial"],
    specialRequestsPlaceholder: "Informacion adicional (motivo de consulta, si es primera vez, preferencia de modalidad)...",
  },
  nutricion: {
    value: "nutricion",
    label: "Nutricionista",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeSublabel: "Selecciona el numero de pacientes.",
    eventTypes: [
      { emoji: "Ensalada", label: "Consulta nutricional" },
      { emoji: "Control", label: "Control y seguimiento" },
      { emoji: "Deporte", label: "Nutricion deportiva" },
      { emoji: "Medico", label: "Nutricion clinica" },
      { emoji: "Bebe", label: "Nutricion materno-infantil" },
      { emoji: "Peso", label: "Plan de alimentacion" },
    ],
    specialChips: ["Primera vez", "Diabetes", "Hipertension", "Intolerancia lactosa", "Vegetariano/Vegano"],
    specialRequestsPlaceholder: "Detalles adicionales (condiciones de salud, restricciones alimenticias, objetivo)...",
  },
  fisioterapia: {
    value: "fisioterapia",
    label: "Centro de Fisioterapia",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeSublabel: "Selecciona el numero de pacientes.",
    eventTypes: [
      { emoji: "Lesion", label: "Rehabilitacion de lesion" },
      { emoji: "Columna", label: "Dolor lumbar / columna" },
      { emoji: "Deporte", label: "Fisioterapia deportiva" },
      { emoji: "Post-op", label: "Post operatorio" },
      { emoji: "Rodilla", label: "Articulaciones" },
      { emoji: "Postura", label: "Reeducacion postural" },
    ],
    specialChips: ["Primera vez", "Post operatorio", "Remision medica", "Paciente con movilidad reducida", "Domicilio"],
    specialRequestsPlaceholder: "Detalles adicionales (area afectada, tiempo de lesion, tratamiento previo)...",
  },
  laboratorio: {
    value: "laboratorio",
    label: "Laboratorio Clinico",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeSublabel: "Selecciona el numero de pacientes.",
    eventTypes: [
      { emoji: "Sangre", label: "Toma de muestra sangre" },
      { emoji: "Orina", label: "Muestra de orina" },
      { emoji: "Biopsia", label: "Biopsia" },
      { emoji: "Imagen", label: "Imagenologia" },
      { emoji: "PCR", label: "Prueba PCR" },
      { emoji: "Resultados", label: "Entrega de resultados" },
    ],
    specialChips: ["Ayunas requerido", "Orden medica", "Urgente", "Menor de edad", "Domicilio"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de examen, si va en ayunas, orden medica adjunta)...",
  },
  eps_ips: {
    value: "eps_ips",
    label: "EPS / IPS",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeSublabel: "Selecciona el numero de pacientes.",
    eventTypes: [
      { emoji: "Medico", label: "Consulta general" },
      { emoji: "Vacuna", label: "Vacunacion" },
      { emoji: "Examen", label: "Examenes de laboratorio" },
      { emoji: "Prenatal", label: "Control prenatal" },
      { emoji: "Nino", label: "Pediatria" },
      { emoji: "Mental", label: "Salud mental" },
    ],
    specialChips: ["Autorizacion previa", "Remision especialista", "Control preventivo", "Urgencia", "Primer Control"],
    specialRequestsPlaceholder: "Detalles adicionales (numero de autorizacion, especialidad requerida, motivo)...",
  },
  farmacia: {
    value: "farmacia",
    label: "Farmacia / Drogueria",
    category: "Salud",
    partySizeLabel: "Clientes",
    partySizeSublabel: "Selecciona el numero de clientes.",
    eventTypes: [
      { emoji: "Farmaco", label: "Entrega de medicamentos" },
      { emoji: "Formula", label: "Formulacion medica" },
      { emoji: "Asesoria", label: "Asesoria farmaceutica" },
      { emoji: "Vacuna", label: "Vacunacion en farmacia" },
      { emoji: "Prueba", label: "Prueba diagnostica" },
      { emoji: "Insumos", label: "Insumos medicos" },
    ],
    specialChips: ["Formula medica", "Medicamento controlado", "Aseguradora", "Urgente", "Domicilio"],
    specialRequestsPlaceholder: "Detalles adicionales (medicamentos solicitados, numero de formula, aseguradora)...",
  },
  veterinaria: {
    value: "veterinaria",
    label: "Veterinaria",
    category: "Servicios",
    partySizeLabel: "Mascotas",
    partySizeSublabel: "Selecciona el numero de mascotas.",
    eventTypes: [
      { emoji: "Perro", label: "Consulta general" },
      { emoji: "Vacuna", label: "Vacunacion" },
      { emoji: "Bano", label: "Peluqueria y bano" },
      { emoji: "Control", label: "Control de salud" },
      { emoji: "Emergencia", label: "Emergencia veterinaria" },
      { emoji: "Cirugia", label: "Cirugia" },
    ],
    specialChips: ["Perro", "Gato", "Ave", "Roedor", "Reptil", "Primera vez", "Urgencia"],
    specialRequestsPlaceholder: "Detalles adicionales (especie, raza, edad, motivo de consulta)...",
  },
  peluqueria: {
    value: "peluqueria",
    label: "Peluqueria / Barberia",
    category: "Belleza",
    partySizeLabel: "Clientes",
    partySizeSublabel: "Selecciona el numero de clientes.",
    eventTypes: [
      { emoji: "Tijeras", label: "Corte de cabello" },
      { emoji: "Barba", label: "Arreglo de barba" },
      { emoji: "Color", label: "Coloracion / Tinte" },
      { emoji: "Tratamiento", label: "Tratamiento capilar" },
      { emoji: "Peinado", label: "Peinado y estilo" },
      { emoji: "Alisado", label: "Alisado / Queratina" },
    ],
    specialChips: ["Primera vez", "Cabello largo", "Cabello danado", "Urgente", "Servicio a domicilio"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de cabello, servicio especifico, estilista preferido)...",
  },
  manicure: {
    value: "manicure",
    label: "Manicure / Pedicure",
    category: "Belleza",
    partySizeLabel: "Clientes",
    partySizeSublabel: "Selecciona el numero de clientes.",
    eventTypes: [
      { emoji: "Mano", label: "Manicure clasico" },
      { emoji: "Pie", label: "Pedicure" },
      { emoji: "Gel", label: "Esmaltado en gel" },
      { emoji: "Acrilico", label: "Unas acrilicas" },
      { emoji: "Arte", label: "Nail art" },
      { emoji: "Semipermanente", label: "Semipermanente" },
    ],
    specialChips: ["Primera vez", "Durazno / Acrilico", "Unas dañadas", "Diseno personalizado", "Manicure + Pedicure"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de esmalte, diseno especifico, alergias)...",
  },
  tatuajes: {
    value: "tatuajes",
    label: "Estudio de Tatuajes",
    category: "Belleza",
    partySizeLabel: "Clientes",
    partySizeSublabel: "Selecciona el numero de clientes.",
    eventTypes: [
      { emoji: "Aguja", label: "Tatuaje nuevo" },
      { emoji: "Retoque", label: "Retoque de tatuaje" },
      { emoji: "Cover", label: "Cover / cubrimiento" },
      { emoji: "Microblading", label: "Microblading / cejas" },
      { emoji: "Piercing", label: "Piercing" },
      { emoji: "Consultoria", label: "Consultoria de diseno" },
    ],
    specialChips: ["Primera vez", "Piel sensible", "Alergia a tintas", "Traer diseno", "Zona visible"],
    specialRequestsPlaceholder: "Detalles adicionales (zona del cuerpo, tamano aproximado, estilo, referencias de diseno)...",
  },
  abogados: {
    value: "abogados",
    label: "Firma de Abogados",
    category: "Servicios Profesionales",
    partySizeLabel: "Clientes",
    partySizeSublabel: "Selecciona el numero de clientes.",
    eventTypes: [
      { emoji: "Documento", label: "Consulta legal" },
      { emoji: "Contrato", label: "Revision de contrato" },
      { emoji: "Familia", label: "Derecho de familia" },
      { emoji: "Laboral", label: "Derecho laboral" },
      { emoji: "Empresa", label: "Derecho comercial" },
      { emoji: "Penal", label: "Derecho penal" },
    ],
    specialChips: ["Primera consulta", "Urgente", "Traer documentos", "Confidencial", "Mediacion"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de caso, documentos a revisar, urgencia del asunto)...",
  },
  contadores: {
    value: "contadores",
    label: "Contadores / Asesores",
    category: "Servicios Profesionales",
    partySizeLabel: "Clientes",
    partySizeSublabel: "Selecciona el numero de clientes.",
    eventTypes: [
      { emoji: "Calculos", label: "Declaracion de renta" },
      { emoji: "Empresa", label: "Asesoria empresarial" },
      { emoji: "Impuesto", label: "Tramite tributario" },
      { emoji: "Nomina", label: "Gestion de nomina" },
      { emoji: "Auditoria", label: "Auditoria contable" },
      { emoji: "Planeacion", label: "Planeacion financiera" },
    ],
    specialChips: ["Primera vez", "Urgente", "Traer documentos", "DIAN", "Empresa nueva"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de asesoría, documentos a revisar, año fiscal)...",
  },
  notaria: {
    value: "notaria",
    label: "Notaria",
    category: "Servicios Profesionales",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Escritura", label: "Escritura publica" },
      { emoji: "Poder", label: "Poder notarial" },
      { emoji: "Matrimonio", label: "Matrimonio civil" },
      { emoji: "Defuncion", label: "Declaracion extra-juicio" },
      { emoji: "Herencia", label: "Sucesion" },
      { emoji: "Reconocimiento", label: "Reconocimiento de firma" },
    ],
    specialChips: ["Traer cedula", "Testigos requeridos", "Urgente", "Varios documentos", "Consulta previa"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de tramite, documentos a autenticar, numero de partes)...",
  },
  inmobiliaria: {
    value: "inmobiliaria",
    label: "Agencia Inmobiliaria",
    category: "Servicios Profesionales",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Casa", label: "Visita a inmueble" },
      { emoji: "Arriendo", label: "Tramite de arriendo" },
      { emoji: "Compra", label: "Proceso de compra" },
      { emoji: "Venta", label: "Avaluo / venta" },
      { emoji: "Juridico", label: "Asesoria juridica" },
      { emoji: "Inversion", label: "Inversion inmobiliaria" },
    ],
    specialChips: ["Primera vez", "Comprador", "Arrendatario", "Inversionista", "Necesita financiacion"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de inmueble buscado, presupuesto, zona de interes)...",
  },
  taller_automotriz: {
    value: "taller_automotriz",
    label: "Taller Automotriz",
    category: "Servicios Tecnicos",
    partySizeLabel: "Vehiculos",
    partySizeSublabel: "Selecciona el numero de vehiculos.",
    eventTypes: [
      { emoji: "Auto", label: "Mantenimiento preventivo" },
      { emoji: "Llave", label: "Revision general" },
      { emoji: "Motor", label: "Reparacion de motor" },
      { emoji: "Frenos", label: "Sistema de frenos" },
      { emoji: "Electrico", label: "Sistema electrico" },
      { emoji: "Enderezada", label: "Latoneria y pintura" },
    ],
    specialChips: ["Urgente", "Garantia", "Seguro", "Traer SOAT", "Primera revision"],
    specialRequestsPlaceholder: "Detalles adicionales (marca, modelo, año del vehiculo, problema reportado)...",
  },
  transito: {
    value: "transito",
    label: "Transito / Traspasos",
    category: "Gobierno",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Auto", label: "Traspaso de vehiculo" },
      { emoji: "Licencia", label: "Licencia de conduccion" },
      { emoji: "Moto", label: "Matricula de vehiculo" },
      { emoji: "Cambio", label: "Cambio de propietario" },
      { emoji: "Certificado", label: "Certificado de tradicion" },
      { emoji: "Comparendo", label: "Tramite de comparendo" },
    ],
    specialChips: ["Primera vez", "Renovacion", "Duplicado", "Examen medico requerido", "Documentos listos"],
    specialRequestsPlaceholder: "Detalles adicionales (placa del vehiculo, tipo de tramite, documentos a llevar)...",
  },
  gobierno: {
    value: "gobierno",
    label: "Oficina Gubernamental",
    category: "Gobierno",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Documento", label: "Tramite de documentos" },
      { emoji: "Solicitud", label: "Solicitud de servicios" },
      { emoji: "Certificado", label: "Certificados" },
      { emoji: "Subsidio", label: "Subsidios y beneficios" },
      { emoji: "Denuncia", label: "Denuncia o reclamo" },
      { emoji: "Info", label: "Informacion general" },
    ],
    specialChips: ["Primera vez", "Traer documentos", "Urgente", "Discapacidad", "Adulto mayor"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de tramite, documentos requeridos, numero de radicado)...",
  },
  academia: {
    value: "academia",
    label: "Academia / Educacion",
    category: "Educacion",
    partySizeLabel: "Estudiantes",
    partySizeSublabel: "Selecciona el numero de estudiantes.",
    eventTypes: [
      { emoji: "Libro", label: "Clase particular" },
      { emoji: "Grupo", label: "Clase grupal" },
      { emoji: "Idioma", label: "Clase de idiomas" },
      { emoji: "Arte", label: "Clase de arte / musica" },
      { emoji: "Prueba", label: "Evaluacion diagnostica" },
      { emoji: "Matricula", label: "Proceso de matricula" },
    ],
    specialChips: ["Primera vez", "Nino / Adolescente", "Adulto mayor", "Virtual disponible", "Pago anticipado"],
    specialRequestsPlaceholder: "Detalles adicionales (nivel actual, objetivo de aprendizaje, horario preferido)...",
  },
  gimnasio: {
    value: "gimnasio",
    label: "Gimnasio / Centro Deportivo",
    category: "Ocio",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Pesas", label: "Clase de pesas" },
      { emoji: "Cardio", label: "Clase de cardio" },
      { emoji: "Yoga", label: "Yoga / Pilates" },
      { emoji: "Spinning", label: "Spinning / Cycling" },
      { emoji: "Boxeo", label: "Boxeo / Artes marciales" },
      { emoji: "Personal", label: "Entrenamiento personal" },
    ],
    specialChips: ["Primera vez", "Principiante", "Lesion previa", "Embarazada", "Adulto mayor"],
    specialRequestsPlaceholder: "Detalles adicionales (objetivo, nivel de experiencia, lesiones o limitaciones)...",
  },
  hotel: {
    value: "hotel",
    label: "Hotel / Hostal",
    category: "Hospitalidad",
    partySizeLabel: "Huespedes",
    partySizeSublabel: "Selecciona el numero de huespedes.",
    eventTypes: [
      { emoji: "Maleta", label: "Alojamiento estandar" },
      { emoji: "Luna de miel", label: "Luna de miel" },
      { emoji: "Familia", label: "Viaje en familia" },
      { emoji: "Negocios", label: "Viaje de negocios" },
      { emoji: "Aventura", label: "Turismo de aventura" },
      { emoji: "Grupo", label: "Grupo / Tour" },
    ],
    specialChips: ["Early check-in", "Late check-out", "Habitacion doble", "Vista al mar", "Mascotas"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de habitacion, fechas de llegada y salida, peticiones especiales)...",
  },
  salon_eventos: {
    value: "salon_eventos",
    label: "Salon de Eventos",
    category: "Ocio",
    partySizeLabel: "Invitados",
    partySizeSublabel: "Selecciona el numero de invitados esperados.",
    eventTypes: [
      { emoji: "Boda", label: "Boda / Matrimonio" },
      { emoji: "Fiesta", label: "Fiesta de cumpleanos" },
      { emoji: "Empresa", label: "Evento corporativo" },
      { emoji: "Grado", label: "Grado / Graduacion" },
      { emoji: "Bautizo", label: "Bautizo / Primera comunion" },
      { emoji: "Otro", label: "Otro evento social" },
    ],
    specialChips: ["Catering incluido", "Decoracion", "DJ / Musica", "Bar abierto", "Ninos asistiran"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de evento, numero de invitados, fecha tentativa, servicios adicionales)...",
  },
  coworking: {
    value: "coworking",
    label: "Coworking / Oficinas",
    category: "Servicios",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Escritorio", label: "Puesto de trabajo" },
      { emoji: "Sala", label: "Sala de reuniones" },
      { emoji: "Evento", label: "Evento / Taller" },
      { emoji: "Oficina", label: "Oficina privada" },
      { emoji: "Foto", label: "Estudio fotografico" },
      { emoji: "Podcast", label: "Estudio de podcast" },
    ],
    specialChips: ["Internet de alta velocidad", "Impresora", "Proyector", "Toma corriente adicional", "Cafe incluido"],
    specialRequestsPlaceholder: "Detalles adicionales (numero de personas, equipo requerido, tipo de trabajo)...",
  },
  otro: {
    value: "otro",
    label: "Otro",
    category: "General",
    partySizeLabel: "Personas",
    partySizeSublabel: "Selecciona el numero de personas.",
    eventTypes: [
      { emoji: "Estrella", label: "Cita general" },
      { emoji: "Agenda", label: "Reunion" },
      { emoji: "Consulta", label: "Consulta" },
      { emoji: "Servicio", label: "Servicio" },
      { emoji: "Tramite", label: "Tramite" },
      { emoji: "Otro", label: "Otro" },
    ],
    specialChips: ["Primera vez", "Urgente", "Traer documentos", "Accesibilidad"],
    specialRequestsPlaceholder: "Detalles adicionales sobre tu reserva...",
  },
}

/** All 30 business types grouped by category for the onboarding selector */
export const BUSINESS_TYPE_GROUPS: Array<{ category: string; types: BusinessTypeConfig[] }> = [
  {
    category: "Gastronomia",
    types: ["restaurante", "bar", "cafe", "fast_food"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Salud",
    types: ["clinica_dental", "consultorio_medico", "eps_ips", "farmacia", "psicologia", "nutricion", "fisioterapia", "laboratorio"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Salud y Belleza",
    types: ["centro_estetica", "peluqueria", "manicure", "tatuajes", "veterinaria"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Servicios Profesionales",
    types: ["abogados", "contadores", "notaria", "inmobiliaria"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Servicios Tecnicos y Otros",
    types: ["taller_automotriz", "coworking"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Gobierno y Tramites",
    types: ["transito", "gobierno"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Educacion y Ocio",
    types: ["academia", "gimnasio", "hotel", "salon_eventos"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "General",
    types: ["otro"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
]

/**
 * Returns config for a given business type string.
 * Falls back to "otro" if the type is unknown.
 */
export function getBusinessTypeConfig(type: string | null | undefined): BusinessTypeConfig {
  if (type && BUSINESS_TYPE_CONFIGS[type]) {
    return BUSINESS_TYPE_CONFIGS[type]
  }
  return BUSINESS_TYPE_CONFIGS["otro"]
}
