/**
 * Business types catalog for iAgend.
 * Each type defines event options, special request chips, and UI labels
 * that are contextually appropriate for that type of establishment.
 */

export interface EventType {
  emoji: string
  label: string
}

export interface BusinessTypeConfig {
  value: string
  label: string
  category: string
  partySizeLabel: string
  partySizeQuestion: string
  partySizeSublabel: string
  maxPartySize: number
  eventTypes: EventType[]
  specialChips: string[]
  specialRequestsPlaceholder: string
}

export const BUSINESS_TYPE_CONFIGS: Record<string, BusinessTypeConfig> = {
  restaurante: {
    value: "restaurante",
    label: "Restaurante",
    category: "Gastronomia",
    partySizeLabel: "Comensales",
    partySizeQuestion: "¿Cuántos comensales?",
    partySizeSublabel: "Selecciona la cantidad de personas.",
    maxPartySize: 15,
    eventTypes: [
      { emoji: "🍽️", label: "Cena casual" },
      { emoji: "💑", label: "Cena romántica" },
      { emoji: "🎂", label: "Cumpleaños" },
      { emoji: "🥂", label: "Aniversario" },
      { emoji: "💼", label: "Negocios" },
      { emoji: "🎉", label: "Celebración" },
    ],
    specialChips: ["Silla para bebé", "Accesibilidad", "Mesa tranquila", "Vista panorámica", "Alergias"],
    specialRequestsPlaceholder: "Solicitudes adicionales (alergias, mesa preferida, coche bebé)...",
  },
  bar: {
    value: "bar",
    label: "Bar / Pub",
    category: "Gastronomia",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 15,
    eventTypes: [
      { emoji: "🍺", label: "Reunión informal" },
      { emoji: "🎉", label: "Celebración" },
      { emoji: "🎂", label: "Cumpleaños" },
      { emoji: "🎵", label: "Noche de música" },
      { emoji: "📺", label: "Ver partido" },
      { emoji: "🥂", label: "Despedida" },
    ],
    specialChips: ["Mesa reservada", "Zona VIP", "Sin ruido", "Accesibilidad", "Botella compartida"],
    specialRequestsPlaceholder: "Solicitudes adicionales (zona preferida, decoración, bebidas especiales)...",
  },
  cafe: {
    value: "cafe",
    label: "Cafetería",
    category: "Gastronomia",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 10,
    eventTypes: [
      { emoji: "☕", label: "Reunión casual" },
      { emoji: "💻", label: "Trabajo remoto" },
      { emoji: "📖", label: "Estudio" },
      { emoji: "💼", label: "Reunión de negocios" },
      { emoji: "👥", label: "Encuentro amigos" },
      { emoji: "💑", label: "Cita romántica" },
    ],
    specialChips: ["Mesa de trabajo", "Toma corriente", "Zona tranquila", "Accesibilidad", "Mesa exterior"],
    specialRequestsPlaceholder: "Solicitudes adicionales (mesa con toma corriente, zona tranquila)...",
  },
  fast_food: {
    value: "fast_food",
    label: "Comida Rápida",
    category: "Gastronomia",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 12,
    eventTypes: [
      { emoji: "🍔", label: "Almuerzo rápido" },
      { emoji: "👨‍👩‍👧‍👦", label: "Reunión familiar" },
      { emoji: "🎂", label: "Cumpleaños" },
      { emoji: "👶", label: "Salida con niños" },
      { emoji: "👥", label: "Salida con amigos" },
      { emoji: "💼", label: "Hora del almuerzo" },
    ],
    specialChips: ["Silla para bebé", "Área infantil", "Accesibilidad", "Para llevar", "Alergias"],
    specialRequestsPlaceholder: "Solicitudes adicionales (alergias, área infantil)...",
  },
  clinica_dental: {
    value: "clinica_dental",
    label: "Clínica Dental",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeQuestion: "¿Cuántos pacientes?",
    partySizeSublabel: "Selecciona el número de pacientes.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "🦷", label: "Limpieza dental" },
      { emoji: "😬", label: "Ortodoncia" },
      { emoji: "✨", label: "Blanqueamiento" },
      { emoji: "🩺", label: "Consulta general" },
      { emoji: "🏥", label: "Endodoncia" },
      { emoji: "😁", label: "Diseño de sonrisa" },
    ],
    specialChips: ["Primera vez", "Control post-tratamiento", "Urgencia dental", "Paciente menor de edad", "Fobia al dentista"],
    specialRequestsPlaceholder: "Detalles adicionales (tratamiento previo, alergias a anestesia, urgencia)...",
  },
  consultorio_medico: {
    value: "consultorio_medico",
    label: "Consultorio Médico",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeQuestion: "¿Cuántos pacientes?",
    partySizeSublabel: "Selecciona el número de pacientes.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "🩺", label: "Consulta general" },
      { emoji: "🔄", label: "Control médico" },
      { emoji: "📄", label: "Entrega de resultados" },
      { emoji: "👨‍⚕️", label: "Especialista" },
      { emoji: "🛡️", label: "Chequeo preventivo" },
      { emoji: "🚨", label: "Urgencia médica" },
    ],
    specialChips: ["Primera vez", "Control periódico", "Remisión especialista", "Traer exámenes", "Paciente con movilidad reducida"],
    specialRequestsPlaceholder: "Detalles adicionales (motivo de consulta, medicamentos actuales, alergias)...",
  },
  centro_estetica: {
    value: "centro_estetica",
    label: "Centro de Estética / Spa",
    category: "Salud y Belleza",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "💆‍♀️", label: "Sesión de spa" },
      { emoji: "💆", label: "Masaje relajante" },
      { emoji: "✨", label: "Tratamiento facial" },
      { emoji: "🧴", label: "Tratamiento corporal" },
      { emoji: "💑", label: "Spa en pareja" },
      { emoji: "🎂", label: "Cumpleaños spa" },
    ],
    specialChips: ["Primera vez", "Embarazada", "Piel sensible", "Alergias a productos", "Servicio de pareja"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de piel, alergias a productos, preferencia de terapeuta)...",
  },
  psicologia: {
    value: "psicologia",
    label: "Psicólogo / Terapeuta",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeQuestion: "¿Cuántos pacientes?",
    partySizeSublabel: "Selecciona el número de pacientes.",
    maxPartySize: 2,
    eventTypes: [
      { emoji: "🧠", label: "Consulta individual" },
      { emoji: "💑", label: "Terapia de pareja" },
      { emoji: "👨‍👩‍👧‍👦", label: "Terapia familiar" },
      { emoji: "👶", label: "Psicología infantil" },
      { emoji: "💼", label: "Psicología laboral" },
      { emoji: "📝", label: "Evaluación psicológica" },
    ],
    specialChips: ["Primera vez", "Derivación médica", "Crisis emocional", "Modalidad virtual", "Confidencial"],
    specialRequestsPlaceholder: "Información adicional (motivo de consulta, si es primera vez, preferencia de modalidad)...",
  },
  nutricion: {
    value: "nutricion",
    label: "Nutricionista",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeQuestion: "¿Cuántos pacientes?",
    partySizeSublabel: "Selecciona el número de pacientes.",
    maxPartySize: 2,
    eventTypes: [
      { emoji: "🥗", label: "Consulta nutricional" },
      { emoji: "🔄", label: "Control y seguimiento" },
      { emoji: "🏃", label: "Nutrición deportiva" },
      { emoji: "🩺", label: "Nutrición clínica" },
      { emoji: "👶", label: "Nutrición materno-infantil" },
      { emoji: "📊", label: "Plan de alimentación" },
    ],
    specialChips: ["Primera vez", "Diabetes", "Hipertensión", "Intolerancia lactosa", "Vegetariano/Vegano"],
    specialRequestsPlaceholder: "Detalles adicionales (condiciones de salud, restricciones alimenticias, objetivo)...",
  },
  fisioterapia: {
    value: "fisioterapia",
    label: "Centro de Fisioterapia",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeQuestion: "¿Cuántos pacientes?",
    partySizeSublabel: "Selecciona el número de pacientes.",
    maxPartySize: 2,
    eventTypes: [
      { emoji: "💪", label: "Rehabilitación de lesión" },
      { emoji: "🦴", label: "Dolor lumbar / columna" },
      { emoji: "🏃", label: "Fisioterapia deportiva" },
      { emoji: "🏥", label: "Post operatorio" },
      { emoji: "🦵", label: "Articulaciones" },
      { emoji: "🧘", label: "Reeducación postural" },
    ],
    specialChips: ["Primera vez", "Post operatorio", "Remisión médica", "Paciente con movilidad reducida", "Domicilio"],
    specialRequestsPlaceholder: "Detalles adicionales (área afectada, tiempo de lesión, tratamiento previo)...",
  },
  laboratorio: {
    value: "laboratorio",
    label: "Laboratorio Clínico",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeQuestion: "¿Cuántos pacientes?",
    partySizeSublabel: "Selecciona el número de pacientes.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "🩸", label: "Toma de muestra sangre" },
      { emoji: "🧪", label: "Muestra de orina" },
      { emoji: "🔬", label: "Biopsia" },
      { emoji: "🖼️", label: "Imagenología" },
      { emoji: "🦠", label: "Prueba PCR" },
      { emoji: "📄", label: "Entrega de resultados" },
    ],
    specialChips: ["Ayunas requerido", "Orden médica", "Urgente", "Menor de edad", "Domicilio"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de examen, si va en ayunas, orden médica adjunta)...",
  },
  eps_ips: {
    value: "eps_ips",
    label: "EPS / IPS",
    category: "Salud",
    partySizeLabel: "Pacientes",
    partySizeQuestion: "¿Cuántos pacientes?",
    partySizeSublabel: "Selecciona el número de pacientes.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "🩺", label: "Consulta general" },
      { emoji: "💉", label: "Vacunación" },
      { emoji: "🔬", label: "Exámenes de laboratorio" },
      { emoji: "🤰", label: "Control prenatal" },
      { emoji: "👶", label: "Pediatría" },
      { emoji: "🧠", label: "Salud mental" },
    ],
    specialChips: ["Autorización previa", "Remisión especialista", "Control preventivo", "Urgencia", "Primer Control"],
    specialRequestsPlaceholder: "Detalles adicionales (número de autorización, especialidad requerida, motivo)...",
  },
  farmacia: {
    value: "farmacia",
    label: "Farmacia / Droguería",
    category: "Salud",
    partySizeLabel: "Clientes",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de clientes.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "💊", label: "Entrega de medicamentos" },
      { emoji: "📄", label: "Formulación médica" },
      { emoji: "🗣️", label: "Asesoría farmacéutica" },
      { emoji: "💉", label: "Vacunación en farmacia" },
      { emoji: "🧪", label: "Prueba diagnóstica" },
      { emoji: "📦", label: "Insumos médicos" },
    ],
    specialChips: ["Fórmula médica", "Medicamento controlado", "Aseguradora", "Urgente", "Domicilio"],
    specialRequestsPlaceholder: "Detalles adicionales (medicamentos solicitados, número de fórmula, aseguradora)...",
  },
  veterinaria: {
    value: "veterinaria",
    label: "Veterinaria",
    category: "Servicios",
    partySizeLabel: "Mascotas",
    partySizeQuestion: "¿Cuántas mascotas?",
    partySizeSublabel: "Selecciona el número de mascotas.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "🐶", label: "Consulta general" },
      { emoji: "💉", label: "Vacunación" },
      { emoji: "🐱", label: "Peluquería y baño" },
      { emoji: "🦜", label: "Control de salud" },
      { emoji: "🐹", label: "Emergencia veterinaria" },
      { emoji: "🏥", label: "Cirugía" },
    ],
    specialChips: ["Perro", "Gato", "Ave", "Roedor", "Reptil", "Primera vez", "Urgencia"],
    specialRequestsPlaceholder: "Detalles adicionales (especie, raza, edad, motivo de consulta)...",
  },
  peluqueria: {
    value: "peluqueria",
    label: "Peluquería / Barbería",
    category: "Belleza",
    partySizeLabel: "Clientes",
    partySizeQuestion: "¿Cuántos clientes?",
    partySizeSublabel: "Selecciona el número de clientes.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "✂️", label: "Corte de cabello" },
      { emoji: "🪒", label: "Arreglo de barba" },
      { emoji: "🎨", label: "Coloración / Tinte" },
      { emoji: "🧴", label: "Tratamiento capilar" },
      { emoji: "💇‍♀️", label: "Peinado y estilo" },
      { emoji: "✨", label: "Alisado / Queratina" },
    ],
    specialChips: ["Primera vez", "Cabello largo", "Cabello dañado", "Urgente", "Servicio a domicilio"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de cabello, servicio específico, estilista preferido)...",
  },
  manicure: {
    value: "manicure",
    label: "Manicure / Pedicure",
    category: "Belleza",
    partySizeLabel: "Clientes",
    partySizeQuestion: "¿Cuántos clientes?",
    partySizeSublabel: "Selecciona el número de clientes.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "💅", label: "Manicure clásico" },
      { emoji: "🦶", label: "Pedicure" },
      { emoji: "✨", label: "Esmaltado en gel" },
      { emoji: "💅", label: "Uñas acrílicas" },
      { emoji: "🎨", label: "Nail art" },
      { emoji: "⏳", label: "Semipermanente" },
    ],
    specialChips: ["Primera vez", "Durazno / Acrílico", "Uñas dañadas", "Diseño personalizado", "Manicure + Pedicure"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de esmalte, diseño específico, alergias)...",
  },
  tatuajes: {
    value: "tatuajes",
    label: "Estudio de Tatuajes",
    category: "Belleza",
    partySizeLabel: "Clientes",
    partySizeQuestion: "¿Cuántos clientes?",
    partySizeSublabel: "Selecciona el número de clientes.",
    maxPartySize: 2,
    eventTypes: [
      { emoji: "✍️", label: "Tatuaje nuevo" },
      { emoji: "🔄", label: "Retoque de tatuaje" },
      { emoji: "🎨", label: "Cover / cubrimiento" },
      { emoji: "👁️", label: "Microblading / cejas" },
      { emoji: "💎", label: "Piercing" },
      { emoji: "🗣️", label: "Consultoría de diseño" },
    ],
    specialChips: ["Primera vez", "Piel sensible", "Alergia a tintas", "Traer diseño", "Zona visible"],
    specialRequestsPlaceholder: "Detalles adicionales (zona del cuerpo, tamaño aproximado, estilo, referencias de diseño)...",
  },
  abogados: {
    value: "abogados",
    label: "Firma de Abogados",
    category: "Servicios Profesionales",
    partySizeLabel: "Clientes",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de clientes.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "⚖️", label: "Consulta legal" },
      { emoji: "📄", label: "Revisión de contrato" },
      { emoji: "👨‍👩‍👧‍👦", label: "Derecho de familia" },
      { emoji: "💼", label: "Derecho laboral" },
      { emoji: "🏢", label: "Derecho comercial" },
      { emoji: "🏛️", label: "Derecho penal" },
    ],
    specialChips: ["Primera consulta", "Urgente", "Traer documentos", "Confidencial", "Mediación"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de caso, documentos a revisar, urgencia del asunto)...",
  },
  contadores: {
    value: "contadores",
    label: "Contadores / Asesores",
    category: "Servicios Profesionales",
    partySizeLabel: "Clientes",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de clientes.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "📊", label: "Declaración de renta" },
      { emoji: "💼", label: "Asesoría empresarial" },
      { emoji: "📝", label: "Trámite tributario" },
      { emoji: "👥", label: "Gestión de nómina" },
      { emoji: "🔍", label: "Auditoría contable" },
      { emoji: "📈", label: "Planeación financiera" },
    ],
    specialChips: ["Primera vez", "Urgente", "Traer documentos", "DIAN", "Empresa nueva"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de asesoría, documentos a revisar, año fiscal)...",
  },
  notaria: {
    value: "notaria",
    label: "Notaría",
    category: "Servicios Profesionales",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 6,
    eventTypes: [
      { emoji: "✍️", label: "Escritura pública" },
      { emoji: "📜", label: "Poder notarial" },
      { emoji: "👰", label: "Matrimonio civil" },
      { emoji: "📝", label: "Declaración extra-juicio" },
      { emoji: "🏛", label: "Sucesión" },
      { emoji: "🖋️", label: "Reconocimiento de firma" },
    ],
    specialChips: ["Traer cédula", "Testigos requeridos", "Urgente", "Varios documentos", "Consulta previa"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de trámite, documentos a autenticar, número de partes)...",
  },
  inmobiliaria: {
    value: "inmobiliaria",
    label: "Agencia Inmobiliaria",
    category: "Servicios Profesionales",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 6,
    eventTypes: [
      { emoji: "🏠", label: "Visita a inmueble" },
      { emoji: "🔑", label: "Trámite de arriendo" },
      { emoji: "🤝", label: "Proceso de compra" },
      { emoji: "💰", label: "Avalúo / venta" },
      { emoji: "⚖️", label: "Asesoría jurídica" },
      { emoji: "📈", label: "Inversión inmobiliaria" },
    ],
    specialChips: ["Primera vez", "Comprador", "Arrendatario", "Inversionista", "Necesita financiación"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de inmueble buscado, presupuesto, zona de interés)...",
  },
  taller_automotriz: {
    value: "taller_automotriz",
    label: "Taller Automotriz",
    category: "Servicios Técnicos",
    partySizeLabel: "Vehículos",
    partySizeQuestion: "¿Cuántos vehículos?",
    partySizeSublabel: "Selecciona el número de vehículos.",
    maxPartySize: 2,
    eventTypes: [
      { emoji: "🚗", label: "Mantenimiento preventivo" },
      { emoji: "🔧", label: "Revisión general" },
      { emoji: "⚙️", label: "Reparación de motor" },
      { emoji: "🛑", label: "Sistema de frenos" },
      { emoji: "⚡", label: "Sistema eléctrico" },
      { emoji: "🎨", label: "Latonería y pintura" },
    ],
    specialChips: ["Urgente", "Garantía", "Seguro", "Traer SOAT", "Primera revisión"],
    specialRequestsPlaceholder: "Detalles adicionales (marca, modelo, año del vehículo, problema reportado)...",
  },
  transito: {
    value: "transito",
    label: "Tránsito / Traspasos",
    category: "Gobierno",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "🚗", label: "Traspaso de vehículo" },
      { emoji: "🪪", label: "Licencia de conducción" },
      { emoji: "🏍️", label: "Matrícula de vehículo" },
      { emoji: "🔄", label: "Cambio de propietario" },
      { emoji: "📄", label: "Certificado de tradición" },
      { emoji: "⚖️", label: "Trámite de comparendo" },
    ],
    specialChips: ["Primera vez", "Renovación", "Duplicado", "Examen médico requerido", "Documentos listos"],
    specialRequestsPlaceholder: "Detalles adicionales (placa del vehículo, tipo de trámite, documentos a llevar)...",
  },
  gobierno: {
    value: "gobierno",
    label: "Oficina Gubernamental",
    category: "Gobierno",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "📄", label: "Trámite de documentos" },
      { emoji: "📋", label: "Solicitud de servicios" },
      { emoji: "📜", label: "Certificados" },
      { emoji: "💰", label: "Subsidios y beneficios" },
      { emoji: "📢", label: "Denuncia o reclamo" },
      { emoji: "ℹ️", label: "Información general" },
    ],
    specialChips: ["Primera vez", "Traer documentos", "Urgente", "Discapacidad", "Adulto mayor"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de trámite, documentos requeridos, número de radicado)...",
  },
  academia: {
    value: "academia",
    label: "Academia / Educación",
    category: "Educación",
    partySizeLabel: "Estudiantes",
    partySizeQuestion: "¿Cuántos estudiantes?",
    partySizeSublabel: "Selecciona el número de estudiantes.",
    maxPartySize: 6,
    eventTypes: [
      { emoji: "📖", label: "Clase particular" },
      { emoji: "👥", label: "Clase grupal" },
      { emoji: "🗣️", label: "Clase de idiomas" },
      { emoji: "🎨", label: "Clase de arte / música" },
      { emoji: "📝", label: "Evaluación diagnóstica" },
      { emoji: "🎓", label: "Proceso de matrícula" },
    ],
    specialChips: ["Primera vez", "Niño / Adolescente", "Adulto mayor", "Virtual disponible", "Pago anticipado"],
    specialRequestsPlaceholder: "Detalles adicionales (nivel actual, objetivo de aprendizaje, horario preferido)...",
  },
  gimnasio: {
    value: "gimnasio",
    label: "Gimnasio / Centro Deportivo",
    category: "Ocio",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 4,
    eventTypes: [
      { emoji: "🏋️‍♂️", label: "Clase de pesas" },
      { emoji: "🏃‍♂️", label: "Clase de cardio" },
      { emoji: "🧘", label: "Yoga / Pilates" },
      { emoji: "🚴", label: "Spinning / Cycling" },
      { emoji: "🥊", label: "Boxeo / Artes marciales" },
      { emoji: "💪", label: "Entrenamiento personal" },
    ],
    specialChips: ["Primera vez", "Principiante", "Lesión previa", "Embarazada", "Adulto mayor"],
    specialRequestsPlaceholder: "Detalles adicionales (objetivo, nivel de experiencia, lesiones o limitaciones)...",
  },
  hotel: {
    value: "hotel",
    label: "Hotel / Hostal",
    category: "Hospitalidad",
    partySizeLabel: "Huéspedes",
    partySizeQuestion: "¿Cuántos huéspedes?",
    partySizeSublabel: "Selecciona el número de huéspedes.",
    maxPartySize: 8,
    eventTypes: [
      { emoji: "🏨", label: "Alojamiento estándar" },
      { emoji: "👩‍❤️‍👨", label: "Luna de miel" },
      { emoji: "👨‍👩‍👧‍👦", label: "Viaje en familia" },
      { emoji: "💼", label: "Viaje de negocios" },
      { emoji: "🧗", label: "Turismo de aventura" },
      { emoji: "👥", label: "Grupo / Tour" },
    ],
    specialChips: ["Early check-in", "Late check-out", "Habitación doble", "Vista al mar", "Mascotas"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de habitación, fechas de llegada y salida, peticiones especiales)...",
  },
  salon_eventos: {
    value: "salon_eventos",
    label: "Salón de Eventos",
    category: "Ocio",
    partySizeLabel: "Invitados",
    partySizeQuestion: "¿Cuántos invitados?",
    partySizeSublabel: "Selecciona el número de invitados esperados.",
    maxPartySize: 15,
    eventTypes: [
      { emoji: "👰", label: "Boda / Matrimonio" },
      { emoji: "🎉", label: "Fiesta de cumpleaños" },
      { emoji: "🏢", label: "Evento corporativo" },
      { emoji: "🎓", label: "Grado / Graduación" },
      { emoji: "⛪", label: "Bautizo / Primera comunión" },
      { emoji: "👥", label: "Otro evento social" },
    ],
    specialChips: ["Catering incluido", "Decoración", "DJ / Música", "Bar abierto", "Niños asistirán"],
    specialRequestsPlaceholder: "Detalles adicionales (tipo de evento, número de invitados, fecha tentativa, servicios adicionales)...",
  },
  coworking: {
    value: "coworking",
    label: "Coworking / Oficinas",
    category: "Servicios",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 10,
    eventTypes: [
      { emoji: "💻", label: "Puesto de trabajo" },
      { emoji: "👥", label: "Sala de reuniones" },
      { emoji: "🎙️", label: "Evento / Taller" },
      { emoji: "🏢", label: "Oficina privada" },
      { emoji: "📸", label: "Estudio fotográfico" },
      { emoji: "🎧", label: "Estudio de podcast" },
    ],
    specialChips: ["Internet de alta velocidad", "Impresora", "Proyector", "Toma corriente adicional", "Café incluido"],
    specialRequestsPlaceholder: "Detalles adicionales (número de personas, equipo requerido, tipo de trabajo)...",
  },
  otro: {
    value: "otro",
    label: "Otro",
    category: "General",
    partySizeLabel: "Personas",
    partySizeQuestion: "¿Cuántas personas?",
    partySizeSublabel: "Selecciona el número de personas.",
    maxPartySize: 10,
    eventTypes: [
      { emoji: "⭐", label: "Cita general" },
      { emoji: "📅", label: "Reunión" },
      { emoji: "👥", label: "Consulta" },
      { emoji: "🛠️", label: "Servicio" },
      { emoji: "📄", label: "Trámite" },
      { emoji: "❓", label: "Otro" },
    ],
    specialChips: ["Primera vez", "Urgente", "Traer documentos", "Accesibilidad"],
    specialRequestsPlaceholder: "Detalles adicionales sobre tu reserva...",
  },
}

export const BUSINESS_TYPE_GROUPS = [
  {
    category: "Gastronomia",
    types: ["restaurante", "bar", "cafe", "fast_food"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Salud",
    types: ["clinica_dental", "consultorio_medico", "eps_ips", "farmacia", "psicologia", "nutricion", "fisioterapia", "laboratorio"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Salud y Belleza",
    types: ["centro_estetica", "peluqueria", "manicure", "tatuajes", "veterinaria"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Servicios Profesionales",
    types: ["abogados", "contadores", "notaria", "inmobiliaria"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Servicios Tecnicos y Otros",
    types: ["taller_automotriz", "coworking"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Gobierno y Tramites",
    types: ["transito", "gobierno"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "Educacion y Ocio",
    types: ["academia", "gimnasio", "hotel", "salon_eventos"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
  {
    category: "General",
    types: ["otro"].map((k) => BUSINESS_TYPE_CONFIGS[k]),
  },
]

export function getBusinessTypeConfig(type: string | null | undefined): BusinessTypeConfig {
  if (type && BUSINESS_TYPE_CONFIGS[type]) {
    return BUSINESS_TYPE_CONFIGS[type]
  }
  return BUSINESS_TYPE_CONFIGS["otro"]
}